<?php

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Register text domain
 *
 * @since 2.0
 */
function ssttbutton_textdomain() {
    load_plugin_textdomain( SSTOPB_TEXT, false, SSTOPB_DIR . '/languages/' );
}
add_action( 'init', 'ssttbutton_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 *
 * @since  2.0
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function ssttbutton_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=simple-scroll-to-top-button.php' ) .'">' . __( 'Settings', SSTOPB_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_'.SSTOPB_BASE, 'ssttbutton_settings_link' );

/**
 * Print additional links to plugin meta row
 *
 * @since 4.0
 */
function ssttbutton_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, 'simple-scroll-to-top-button.php' ) !== false ) {

        $new_links = array(
                           'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8A88KC7TFF6CS" target="_blank"><span class="dashicons dashicons-heart"></span> ' . __( 'Donate', SSTOPB_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', 'ssttbutton_plugin_row_meta', 10, 2 );

/**
 * Register plugin's submenu in the "Settings" Admin Menu
 *
 * @since 4.0
 */
function ssttbutton_register_submenu_page() {
    add_options_page( __( 'Scroll to Top', SSTOPB_TEXT ), __( 'Scroll to Top', SSTOPB_TEXT ), 'manage_options', 'simple-scroll-to-top-button', 'ssttbutton_render_submenu_page' );
}
add_action( 'admin_menu', 'ssttbutton_register_submenu_page' );

/**
 * Register settings
 *
 * @since 4.0
 */
function ssttbutton_register_settings() {
    register_setting( 'ssttbutton_settings_group', 'ssttbutton_settings' );
    register_setting( 'ssttbutton_settings_group', 'ssttbutton_service_info' );
}
add_action( 'admin_init', 'ssttbutton_register_settings' );
